apiVersion: apps/v1
kind: Deployment
metadata:
  name: jecrcdep
spec:
  replicas: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      color : red
  template:
    metadata:
      labels:
        color : red
    spec:
      containers:
      - name: jedepc1
        image: httpd        
        ports:
        - containerPort: 80
