apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc33
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
