apiVersion: v1
kind: ReplicationController
metadata:
  name: myreplica
spec:
  replicas: 4
  selector:
    app: myreplica
  template:
    metadata:
      name: myreplica
      labels:
        app: myreplica
  
    spec:
      containers:
        - name: myreplica
          image: httpd
          ports:
            - containerPort: 80
